services:
  #frontend:
  #  image: social/frontend:latest
  #  build: ./web
  #  networks:
  #    - front-tier
  #    - back-tier
  #  ports:
  #    -3000:3000

  #backend:
  #  image: social/backend:latest
  #  container_name: go-backend
  #  build: .
  #  env_file: 
  #    - .env
  #  networks:
  #    - back-tier
  #  ports:
  #    - 8080:8080
  #  depends_on:
  #    - migration

  database:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

 #migration:
 #  image: migrate/migrate
 #  container_name: database-migration
 #  volumes:
 #    - ./cmd/migrate/migrations:/migrations
 #  entrypoint:
 #    - migrate
 #    - -path
 #    - /migrations
 #    - -database
 #    - ${DB_SRC}
 #    - up
 #  networks:
 #    - back-tier
 #  depends_on:
 #    - database

networks:
  front-tier:
  back-tier:

volumes:
  db-data:
